stages:
  split_dataset:
    cmd: python ./src/split_dataset.py
    deps:
    - ./data/in-header.tsv
    - ./data/out-header.tsv
    - ./data/parsed-pdfs.json
    - ./src/DatasetSplitter/DatasetSplitter.py
    - ./src/split_dataset.py
    params:
    - datasetsplit.dev
    - datasetsplit.test
    - datasetsplit.train
    - datasetsplit.sort_by
    outs:
    - ./data/dev/expected.tsv
    - ./data/dev/in.tsv
    - ./data/test/expected.tsv
    - ./data/test/in.tsv
    - ./data/train/expected.tsv
    - ./data/train/in.tsv

  train_classifier:
    cmd: python ./src/train_fasttext.py
    deps:
    - ./src/SKLearnDS/SKLearnDS.py
    - ./src/train_fasttext.py
    - ./data/dev/expected.tsv
    - ./data/dev/in.tsv
    - ./data/test/expected.tsv
    - ./data/test/in.tsv
    - ./data/train/expected.tsv
    - ./data/train/in.tsv
    - ./data/labels.tsv
    params:
    - fasttext.outputs
    - fasttext.epochs
    - fasttext.lr
    - fasttext.seed
    - fasttext.num_training_samples
    outs:
    - ./models/fasttext/fasttext.bin
    - ./data/train/fasttext.txt

  eval_classifier:
    cmd: python ./src/eval.py
    deps:
    - ./src/eval.py
    - ./models/fasttext/fasttext.bin
    - ./data/labels.tsv
    params:
    - fasttext.epsilon
    outs:
    - ./data/dev/out.tsv
    - ./data/test/out.tsv
    metrics:
    - scores_classification.json:
        cache: false
