stages:
  split_dataset:
    cmd: python ./src/split_dataset.py
    deps:
    - ./data/in-header.tsv
    - ./data/out-header.tsv
    - ./data/parsed-pdfs.json
    - ./src/DatasetSplitter/DatasetSplitter.py
    - ./src/split_dataset.py
    params:
    - datasetsplit.dev
    - datasetsplit.test
    - datasetsplit.train
    - datasetsplit.sort_by
    outs:
    - ./data/dev/expected.tsv
    - ./data/dev/in.tsv
    - ./data/test/expected.tsv
    - ./data/test/in.tsv
    - ./data/train/expected.tsv
    - ./data/train/in.tsv

  train_classifier:
    cmd: python ./src/train_logistic_regression.py
    deps:
    - ./src/SKLearnDS/SKLearnDS.py
    - ./src/train_logistic_regression.py
    - ./data/dev/expected.tsv
    - ./data/dev/processed.tsv
    - ./data/test/expected.tsv
    - ./data/test/processed.tsv
    - ./data/train/expected.tsv
    - ./data/train/processed.tsv
    params:
    - logistic_regression.solver
    - logistic_regression.outputs
    - logistic_regression.seed
    outs:
    - ./data/dev/out.tsv
    - ./data/test/out.tsv
    - ./models/logistic_regression/model.pkl
    - ./models/logistic_regression/vectorizer.pkl
    - ./models/logistic_regression/labels.pkl
    metrics:
      - scores_classification.json:
          cache: false

