stages:
  split_dataset:
    cmd: python ./src/split_dataset.py
    deps:
    - ./data/in-header.tsv
    - ./data/out-header.tsv
    - ./data/parsed_books.json
    - ./src/DatasetSplitter/DatasetSplitter.py
    - ./src/split_dataset.py
    params:
    - datasetsplit.dev
    - datasetsplit.test
    - datasetsplit.train
    - datasetsplit.sort_by
    outs:
    - ./data/dev/expected.tsv
    - ./data/dev/in.tsv
    - ./data/test/expected.tsv
    - ./data/test/in.tsv
    - ./data/train/expected.tsv
    - ./data/train/in.tsv

  rewrite_dataset_to_lm_texts:
    cmd: python ./src/rewrite_dataset.py
    deps:
    - ./src/DatasetRewriter/LanguageModelingRewriter.py
    - ./src/rewrite_dataset.py
    - ./data/dev/in.tsv
    - ./data/test/in.tsv
    - ./data/train/in.tsv
    outs:
    - ./data/dev/processed.tsv
    - ./data/test/processed.tsv
    - ./data/train/processed.tsv

  train_classifier:
    cmd: python ./src/train_petrarq_classifier.py
    deps:
    - ./src/train_petrarq_classifier.py
    - ./src/PetraRQ/ClassificationDataset.py
    - ./src/PetraRQ/PetraRQ.py
    - ./src/PetraRQ/CollateFunction.py
    - ./data/dev/expected.tsv
    - ./data/dev/processed.tsv
    - ./data/test/expected.tsv
    - ./data/test/processed.tsv
    - ./data/train/expected.tsv
    - ./data/train/processed.tsv
    - ./data/labels.tsv
    params:
    - classification_train.epochs
    - classification_train.num_training_samples
    - classification_train.seq_length
    - classification_train.overlapping_part
    - classification_train.lr
    - classification_train.train_batch_size
    - classification_train.seed
    - classification_train.increase_each
    outs:
    - ./models/petrarq_classifier_books/pytorch_model.ckpt

  evaluate_classifier:
    cmd: python ./src/eval.py
    deps:
    - ./models/petrarq_classifier_books/pytorch_model.ckpt
    - ./src/eval.py
    params:
    - classification_eval.epsilon
    outs:
    - ./data/dev/out.tsv
    - ./data/test/out.tsv
    metrics:
      - scores_classification.json:
          cache: false
