stages:
  split_dataset:
    cmd: python ./src/split_dataset.py
    deps:
    - ./data/in-header.tsv
    - ./data/out-header.tsv
    - ./data/parsed-pdfs.json
    - ./src/DatasetSplitter/DatasetSplitter.py
    - ./src/split_dataset.py
    params:
    - datasetsplit.dev
    - datasetsplit.test
    - datasetsplit.train
    outs:
    - ./data/dev/expected.tsv
    - ./data/dev/in.tsv
    - ./data/test/expected.tsv
    - ./data/test/in.tsv
    - ./data/train/expected.tsv
    - ./data/train/in.tsv

  rewrite_dataset_to_lm_texts:
    cmd: python ./src/rewrite_dataset.py
    deps:
    - ./src/DatasetRewriter/LanguageModelingRewriter.py
    - ./src/rewrite_dataset.py
    - ./data/dev/in.tsv
    - ./data/test/in.tsv
    - ./data/train/in.tsv
    outs:
    - ./data/dev/lm.txt
    - ./data/test/lm.txt
    - ./data/train/lm.txt
    - ./data/dev/processed.tsv
    - ./data/test/processed.tsv
    - ./data/train/processed.tsv

  train_classifier:
    cmd: python ./src/train_svm.py
    deps:
    - ./src/SKLearnDS/SKLearnDS.py
    - ./src/train_svm.py
    - ./data/dev/expected.tsv
    - ./data/dev/processed.tsv
    - ./data/test/expected.tsv
    - ./data/test/processed.tsv
    - ./data/train/expected.tsv
    - ./data/train/processed.tsv
    outs:
    - ./data/dev/out.tsv
    - ./data/test/out.tsv
    - ./models/svm/model.pkl
    metrics:
      - scores_classification.json:
          cache: false

