datasetsplit:
  train: 0.85
  test: 0.1
  dev: 0.05
  parts: 3
  sort_by: date #date or hash

classification_train:
  cuda_visible_devices: [5]

  warmup_steps: 200
  num_train_epochs: 20
  num_training_samples: -1

  per_device_train_batch_size: 15
  per_device_eval_batch_size: 20

  outputs: probabilities #labels or probabilities
  seed: 42

classification_eval:
  epsilon: 1e-2
