name: Push to gonito.net

on:
  push:
    branches:
      - 'models/**'

jobs:
  PushToGonito:
    runs-on: self-hosted
    container: python:3.7

    steps:
      - name: Install SSH & git
        run: |
          apt-get update && \
          apt-get upgrade -y && \
          apt-get install -y git ssh

      - name: Add SSH key
        run: chmod +x ./scripts/add_ssh_key.sh && ./scripts/add_ssh_key.sh
        env:
          GONITO_PRIVATE_SSH: ${{secrets.GONITO_PRIVATE_SSH}}

      - name: test cloning
        run: |
            git clone ssh://gitolite@gonito.net/eur-lex-documents

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add needed dirs
        run: mkdir ./.dvc/tmp

      - name: Clone google credentials file
        run: echo $BMARCINAI_GOOGLE_CREDENTIALS > ./.dvc/tmp/gdrive-user-credentials.json
        env:
          BMARCINAI_GOOGLE_CREDENTIALS: ${{secrets.BMARCINAI_GOOGLE_CREDENTIALS}}

      - name: Download & install DVC
        run: apt-get update && apt-get install -y wget && wget https://dvc.org/download/linux-deb/dvc-2.9.4 && dpkg -i dvc-2.9.4

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Makefile
        run: make all

      - name: Set Branch Environment
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Gonito repos
        run: chmod +x ./scripts/build_gonito_submission_repo.sh && ./scripts/build_gonito_submission_repo.sh
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
