name: Repro project

on:
  push:
    branches:
      - 'feature/*'

jobs:
  ReproProject:
    runs-on: self-hosted
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add needed dirs
        run: mkdir ./.dvc/tmp

      - name: Clone google credentials file
        run: echo $BMARCINAI_GOOGLE_CREDENTIALS > ./.dvc/tmp/gdrive-user-credentials.json
        env:
          BMARCINAI_GOOGLE_CREDENTIALS: ${{secrets.BMARCINAI_GOOGLE_CREDENTIALS}}

      - name: Download & install DVC
        run: curl -o dvc-2.7.4 -L https://dvc.org/download/linux-deb/dvc-2.7.4 && dpkg -i dvc-2.7.4

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Makefile
        run: make

      - name: Autocommit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'DVC repro done'
          file_pattern: dvc.lock
