name: Build repro image

on:
  push:
    branches:
      - 'models/**'

jobs:
  DockerBuildPush:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Branch Environment
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: docker/repro_cpu.Dockerfile
          pull: true
          context: .
          push: true
          tags: ghcr.io/bmarcin/petrarq:${{ env.BRANCH }}
          cache-from: type=registry,ref=ghcr.io/bmarcin/petrarq:${{ env.BRANCH }}
          cache-to: type=inline
          build-args: |
            BRANCH=${{ env.BRANCH }}

  PushToGonito:
    runs-on: self-hosted
    container: ghcr.io/bmarcin/petrarq